# ========================================================
# REGION DEFINITIONS
# ========================================================
regions:

  indonesia:
    bbox: [90, 150, -15, 15]
    figsize: [9, 7]
    arrowscale: 60
    quiver:
      skip: 4
      scale: 55

  southeast_asia:
    bbox: [80, 160, -25, 25]
    # figsize: [10, 8]
    arrowscale: 90
    quiver:
      skip: 6
      scale: 80

# ========================================================
# GLOBAL FALLBACK DEFAULTS
# ========================================================
defaults:
  proj: mercator
  dpi: 90
  figsize: [8, 6]

# ========================================================
# VARIABLE-SPECIFIC SETTINGS
# ========================================================
variables:

  rainrate:
    cmap: Blues
    clims: [0, 20]

  mslp:
    levels:
      start: 980
      end: 1050
      step: 2
    contour:
      linewidth: 0.7
      interval: 2
  
  temp:
    cmap: RdYlBu_r
    clims: [20, 35]
  
  relhum:
    cmap: BrBG
    clims: [0, 100]

  wind:
    var2display: "Surface Wind Speed and Direction"
    quiver:
      skip: 5
      scale: 40
  
  swh:
    cmap: YlGnBu
    clims: [0, 6]

  swell:
    cmap: PuBuGn
    clims: [0, 6]

  seacurrent:
    quiver:
      skip: 5
      scale: 50

  seatemp:
    cmap: RdYlBu_r
    clims: [20, 35]
  
  seasalt:
    cmap: BrBG
    clims: [0, 35]

  ssh:
    cmap: PuBuGn
    clims: [-1, 1]